name: dart_app_data
description: A package for getting commonly used locations for storage on Windows, Mac, and Linux, such as the app data directories.
version: 1.0.2
homepage: https://github.com/tobischw/dart_app_data
author: tobischw <tschwei@siue.edu>

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  path: ^1.8.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.1
