name: app_cache
description: A package for getting commonly used locations for storage on Windows, Mac, and Linux, such as the app data directories.
version: 1.0.0
homepage: https://tobischw.me
author: tschwei <tschwei@siue.edu>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
